name: Build

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: ['sixteen']

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target: [a52sxq, a53x, a73xq, b0q, g0q, m52xq, o1s, p3s, r0q, r9s, t2s, r9q]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Cleanup
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force

      - name: Setup
        run: |
          sudo apt update && sudo apt install -yq 7zip attr ccache clang ffmpeg libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler webp
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p security
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/unica_platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/unica_platform.x509.pem

      - name: Build ROM
        run: |
          source ./buildenv.sh ${{ matrix.target }}
          ./scripts/build_dependencies.sh
          ./scripts/download_fw.sh
          ./scripts/extract_fw.sh
          ./scripts/make_rom.sh

      - name: Create Release and Upload Asset
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: out/target/product/${{ matrix.target }}/*.zip
          tag_name: ${{ github.run_id }}
          name: "Build ${{ github.run_id }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
