name: Build
permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches: ['sixteen']

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Setup Environment
        run: |
          # Mandatory: Fixes "Committer identity unknown"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Mandatory: Fixes 'cmake' / 'android-tools' build failures
          # We add essential headers and development libraries needed for compilation
          sudo apt update && sudo apt install -yq \
            build-essential cmake pkg-config libusb-1.0-0-dev libssl-dev \
            7zip attr ccache clang ffmpeg webp protobuf-compiler
          
          mkdir -p security
          echo -n "${{ secrets.PLATFORM_KEY_PK8 }}" | base64 --decode > security/unica_platform.pk8
          echo -n "${{ secrets.PLATFORM_KEY_PEM }}" | base64 --decode > security/unica_platform.x509.pem

      - name: Build ROM
        run: |
          source ./buildenv.sh r9q
          # -f forces build, -z enables packaging
          ./scripts/make_rom.sh -f -z

      - name: Create Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: out/**/*.zip
          tag_name: ${{ github.run_id }}
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
